set search_path = 'imdb';

create index company_id_movie_companies on movie_companies(company_id);
create index company_type_id_movie_companies on movie_companies(company_type_id);
create index info_type_id_movie_info_idx on movie_info_idx(info_type_id);
create index info_type_id_movie_info on movie_info(info_type_id);
create index info_type_id_person_info on person_info(info_type_id);
create index keyword_id_movie_keyword on movie_keyword(keyword_id);
create index kind_id_aka_title on aka_title(kind_id);
create index kind_id_title on title(kind_id);
create index linked_movie_id_movie_link on movie_link(linked_movie_id);
create index link_type_id_movie_link on movie_link(link_type_id);
create index movie_id_aka_title on aka_title(movie_id);
create index movie_id_cast_info on cast_info(movie_id);
create index movie_id_complete_cast on complete_cast(movie_id);
create index movie_id_movie_companies on movie_companies(movie_id);
create index movie_id_movie_info_idx on movie_info_idx(movie_id);
create index movie_id_movie_keyword on movie_keyword(movie_id);
create index movie_id_movie_link on movie_link(movie_id);
create index movie_id_movie_info on movie_info(movie_id);
create index person_id_aka_name on aka_name(person_id);
create index person_id_cast_info on cast_info(person_id);
create index person_id_person_info on person_info(person_id);
create index person_role_id_cast_info on cast_info(person_role_id);
create index role_id_cast_info on cast_info(role_id);

create index country_code_company_name on company_name(country_code);
create index name_company_name_pattern on company_name(name text_pattern_ops);
create index kind_company_type on company_type(kind);
create index info_info_type on info_type(info);
create index keyword_keyword on keyword(keyword);
create index kind_kind_type on kind_type(kind);
create index link_link_type on link_type(link);
create index role_role_type on role_type(role);
create index kind_comp_cast_type on comp_cast_type(kind);
create index production_year_title on title(production_year, kind_id);
create index movie_company_type_movie_companies
    on movie_companies(movie_id, company_id, company_type_id);
create index movie_info_type_movie_info on movie_info(movie_id, info_type_id);
create index movie_info_type_movie_info_idx on movie_info_idx(movie_id, info_type_id);
create index movie_keyword_pair on movie_keyword(movie_id, keyword_id);
create index movie_person_role_cast_info on cast_info(movie_id, person_id, role_id);
create index movie_complete_cast on complete_cast(movie_id, subject_id, status_id);
create index movie_link_pair on movie_link(movie_id, linked_movie_id, link_type_id);
create index person_info_pair on person_info(person_id, info_type_id);

analyze aka_name;
analyze aka_title;
analyze cast_info;
analyze char_name;
analyze comp_cast_type;
analyze company_name;
analyze company_type;
analyze complete_cast;
analyze info_type;
analyze keyword;
analyze kind_type;
analyze link_type;
analyze movie_companies;
analyze movie_info;
analyze movie_info_idx;
analyze movie_keyword;
analyze movie_link;
analyze name;
analyze person_info;
analyze role_type;
analyze title;
